# Site settings
title: Chansoo Son
description: 'Software Engineer'
url: 'https://github.com/sonchansoo.github.io'
baseurl: ''
profilepic: '/images/sonchansoo.jpg'
bkimage: '/images/bk2.png'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Chansoo Son'
  email: thsct01@gmail.com
  mastodon: 
  twitter_username: 
#  facebook_username: joshgerdes
  github_username:  sonchansoo
  linkedin_username:  
  meetup_name: 

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']

